<a href="https://colab.research.google.com/github/drod75/cisc3225/blob/main/homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Vector Matrix Addition

In [ ]:
### 2D Matrix addition function

def matrix_add_2d(a, b):
  rows, cols = len(a), len(a[0])
  new_matrix = []
  for i in range(rows):
    new_matrix.append([])
    for j in range(cols):
      new_matrix[i].append(a[i][j] + b[i][j])
  return new_matrix

In [ ]:
%%timeit

a = [[ 4 , 2 , 6 ] ,[ 1 , 9 , 0 ]]

b = [[ 1 , 0 , 0 ] ,[ 4 , 0 , 3 ]]

%timeit -n 10 matrix_add_2d(a, b)

Streaming output truncated to the last 5000 lines.
2.09 µs ± 404 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.02 µs ± 163 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
2 µs ± 128 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
2 µs ± 174 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
2 µs ± 166 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.01 µs ± 184 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.23 µs ± 474 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.15 µs ± 257 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.06 µs ± 224 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.13 µs ± 437 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
2 µs ± 162 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.02 µs ± 166 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.94 µs ± 225 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.96 µs ± 194 ns per loop (mean ± std. dev. of 7 ru

In [ ]:
%%timeit

## testing with larger a/b's

a= [[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]]

b = [[9,8,7,6,5,4,3,2,1],[9,8,7,6,5,4,3,2,1]]

matrix_add_2d(a,b)

2.37 µs ± 46.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
import numpy as np

vector_a = np.array(a)
vector_b = np.array(b)

In [ ]:
%%timeit

np.add(vector_a, vector_b)

795 ns ± 248 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Broadcasting

In [ ]:
### Question 1

a = np.array([
    [1, 1, 2],
    [3, 2, 1],
    [1, 9, 1]
])

b = np.array([
    [1],
    [2],
    [3]
])

a, b

(array([[1, 1, 2],
        [3, 2, 1],
        [1, 9, 1]]),
 array([[1],
        [2],
        [3]]))

In [ ]:
np.add(a, b)

array([[ 2,  2,  3],
       [ 5,  4,  3],
       [ 4, 12,  4]])

In [ ]:
### Question 2

a = np.array([
[
[ 1 , 2 ] ,
[ 3 , 1 ]
] ,
[
[ 8 , 7 ] ,
[ 9 , 1 ]
]
] )
b = np.array( [ 10 , 11 ] )

a.shape,b.shape

((2, 2, 2), (2,))

In [ ]:
np.add(a,b)

array([[[11, 13],
        [13, 12]],

       [[18, 18],
        [19, 12]]])

In [ ]:
### Question 3

a=np.array([1,2,3])
b=np.array([
    [10],
    [11],
    [12]
])

a.shape,b.shape

((3,), (3, 1))

In [ ]:
np.add(a ,b)

array([[11, 12, 13],
       [12, 13, 14],
       [13, 14, 15]])

In [ ]:
### Question 4

a = np.array([
[
[ 1 , 2 ] ,
[ 3 , 1 ]
] ,
[
[ 8 , 7 ] ,
[ 9 , 1 ]
]
] )
b = np.array( [ 10 , 11,12,13 ] )

a.shape,b.shape

((2, 2, 2), (4,))

In [ ]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,2,2) (4,) 

In [ ]:
### Question 5

a = np.array([
    [
        [
            [ 1 ] ,
        ]
    ] ,
    [
        [
            [ 2 ]
        ]
    ]
])
b = np.array( [ 3 , 4 ] )

a.shape,b.shape

((2, 1, 1, 1), (2,))

In [ ]:
np.add(a,b)

array([[[[4, 5]]],


       [[[5, 6]]]])

## Answering Questions with NumPy

In [ ]:
### Loading in data

solardata = np.loadtxt('solar.txt')
solardata.shape

(365, 3)

In [ ]:
testing = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
testing.shape

(3, 3)

In [ ]:
np.mean(testing, axis=0)

array([4., 5., 6.])

In [ ]:
np.mean(testing, axis=1)

array([2., 5., 8.])

In [ ]:
### Sum of all wattage events

np.sum(solardata)

218010.26201750195

In [ ]:
### Max and min of wattage per morning, afternoon, and evening

print(np.max(solardata, axis=0))
print(np.min(solardata, axis=0))

[446.40434207 450.23976606 247.01509894]
[166.23303073   0.           0.        ]


In [ ]:
### Average wattage for January

january_afternoons = solardata[:32, 1:2]
np.average(january_afternoons)

213.90079970179

In [ ]:
solardata < 50

array([[False, False,  True],
       [False,  True, False],
       [False, False, False],
       ...,
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
### Days where wattage is less than 500

solar_500 = solardata[solardata.sum(axis=1) < 500]
solar_500.shape

(89, 3)

In [ ]:
## Average for day, evening, and night

np.average(solardata, axis=0)

array([300.38834891, 198.39523217,  98.50480801])