<a href="https://colab.research.google.com/github/drod75/cisc3225/blob/main/homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 1 (Numpy)

## Vector Matrix Addition

In [1]:
### 2D Matrix addition function

def matrix_add_2d(a, b):
  rows, cols = len(a), len(a[0])
  new_matrix = []
  for i in range(rows):
    new_matrix.append([])
    for j in range(cols):
      new_matrix[i].append(a[i][j] + b[i][j])
  return new_matrix

In [3]:
%%timeit

a = [[ 4 , 2 , 6 ] ,[ 1 , 9 , 0 ]]

b = [[ 1 , 0 , 0 ] ,[ 4 , 0 , 3 ]]

matrix_add_2d(a, b)

9.39 µs ± 3.97 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%%timeit

## testing with larger a/b's

a= [[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]]

b = [[9,8,7,6,5,4,3,2,1],[9,8,7,6,5,4,3,2,1]]

matrix_add_2d(a,b)

3.93 µs ± 421 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
import numpy as np

vector_a = np.array(a)
vector_b = np.array(b)

In [ ]:
%%timeit

np.add(vector_a, vector_b)

989 ns ± 271 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### First time numpy was slower, but now it seems its faster, not sure what changed but numpy seems to be more effecient anyway

## Broadcasting

In [ ]:
### Question 1

a = np.array([
    [1, 1, 2],
    [3, 2, 1],
    [1, 9, 1]
])

b = np.array([
    [1],
    [2],
    [3]
])

a, b

(array([[1, 1, 2],
        [3, 2, 1],
        [1, 9, 1]]),
 array([[1],
        [2],
        [3]]))

In [ ]:
np.add(a, b)

array([[ 2,  2,  3],
       [ 5,  4,  3],
       [ 4, 12,  4]])

In [ ]:
### Question 2

a = np.array([
[
[ 1 , 2 ] ,
[ 3 , 1 ]
] ,
[
[ 8 , 7 ] ,
[ 9 , 1 ]
]
] )
b = np.array( [ 10 , 11 ] )

a.shape,b.shape

((2, 2, 2), (2,))

In [ ]:
np.add(a,b)

array([[[11, 13],
        [13, 12]],

       [[18, 18],
        [19, 12]]])

In [ ]:
### Question 3

a=np.array([1,2,3])
b=np.array([
    [10],
    [11],
    [12]
])

a.shape,b.shape

((3,), (3, 1))

In [ ]:
np.add(a ,b)

array([[11, 12, 13],
       [12, 13, 14],
       [13, 14, 15]])

In [ ]:
### Question 4

a = np.array([
[
[ 1 , 2 ] ,
[ 3 , 1 ]
] ,
[
[ 8 , 7 ] ,
[ 9 , 1 ]
]
] )
b = np.array( [ 10 , 11,12,13 ] )

a.shape,b.shape

((2, 2, 2), (4,))

In [ ]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,2,2) (4,) 

In [ ]:
### Question 5

a = np.array([
    [
        [
            [ 1 ] ,
        ]
    ] ,
    [
        [
            [ 2 ]
        ]
    ]
])
b = np.array( [ 3 , 4 ] )

a.shape,b.shape

((2, 1, 1, 1), (2,))

In [ ]:
np.add(a,b)

array([[[[4, 5]]],


       [[[5, 6]]]])

### Broadcasting is kinda weird and its making my head hurt trying to see which element goes where for these examples but I get it

## Answering Questions with NumPy

In [ ]:
### Loading in data

solardata = np.loadtxt('solar.txt')
solardata.shape

(365, 3)

In [ ]:
testing = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
testing.shape

(3, 3)

In [ ]:
np.mean(testing, axis=0)

array([4., 5., 6.])

In [ ]:
np.mean(testing, axis=1)

array([2., 5., 8.])

### Axis=0 aggregates based on the column, Axis=1 is based on the row

In [ ]:
### Sum of all wattage events

np.sum(solardata)

218010.26201750195

In [ ]:
### Max and min of wattage per morning, afternoon, and evening

print(np.max(solardata, axis=0))
print(np.min(solardata, axis=0))

[446.40434207 450.23976606 247.01509894]
[166.23303073   0.           0.        ]


### Answer should be correct since theres only three elements per vector, meaning only the max/min per column was considered, elese there would be 356 elements per vector

In [ ]:
### Testing for January

solardata[:31]

array([[277.97178749, 290.87848694,  16.27913217],
       [276.79002882,   0.        ,  92.19335012],
       [196.02083865, 126.81410304, 127.24963504],
       [298.0649882 , 164.5728768 ,  91.70748532],
       [257.07155815, 215.55290601, 110.39199191],
       [323.3315445 , 274.99102062, 164.72685376],
       [354.72384951, 149.2298412 , 109.88570971],
       [305.53166165, 134.7595065 ,  54.78380076],
       [247.08196228, 394.87484257, 143.70416869],
       [250.0727405 , 103.39336636,  91.29678034],
       [360.41314527, 351.14251327, 149.3079375 ],
       [320.67253413, 193.92241443, 181.76496417],
       [297.39000994, 355.23036427,  45.84034965],
       [281.8230464 , 187.14855859, 145.85264378],
       [296.57061378,   0.        ,  22.97553758],
       [280.60487936, 261.12396767,  41.7863011 ],
       [281.21314398, 339.26397477, 162.04189884],
       [291.57324724, 181.9679668 ,  46.21146056],
       [254.92957753, 251.81593663,  78.90395902],
       [266.46231132, 240.30437

In [ ]:
### Average wattage for January

january_afternoons = solardata[:31, 1:2]
np.average(january_afternoons)

215.93478827333328

### First slice is to only get the first 31 days, the next is to get only the afternoon (Did it wrong the first time lol)

In [ ]:
solardata < 50

array([[False, False,  True],
       [False,  True, False],
       [False, False, False],
       ...,
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
### Days where wattage is less than 500

solar_500 = solardata[solardata.sum(axis=1) < 500]
solar_500.shape

(89, 3)

### To explain, inside the brackets the rows in solar data are selected based on if there sum is less than 500, this way we get less rows and then we can use shape

In [ ]:
## Average for day, evening, and night

np.average(solardata, axis=0)

array([300.38834891, 198.39523217,  98.50480801])